### ISSUE TITLE
V1.1 chemistry

### ISSUE THREAD

**Issue by ii-bioinfo-thomas** [ScaleBio/ScaleCRISPR#2]
Is it possible to use the pipeline although with the V1.1 kit? I can find only a definition for V1 (libV1.json). If it cannot be used with V1.1 Kit, can you please provide a definition for it. 

Thanks,
Thomas

**Comment by npervolarakis** [comment]
Hi Thomas,

The pipeline can indeed be used with the V1.1 kit by default with no modification using that libV1.json. The naming of that file can be made to be more clear as to which RNA kit version that supports.

Best,

Nick

**Comment by ii-bioinfo-thomas** [comment]
Hi Nick,

thanks for the fast response and clarification.

Best regards,
Thomas
